POST http://95.130.227.160:3300/api/admin
Content-Type: application/json

{
    "name": "Sardor",
    "password": "uzb3",
    "confirm_password": "uzb3",
    "phone": "+0000"

}
###

POST http://95.130.227.160:3300/api/admin/login
Content-Type: application/json

{
    "phone": "+0000",
    "password": "uzb3"

}
###

POST http://localhost:3300/api/admin/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNfYWN0aXZlIjp0cnVlLCJpc19jcmVhdG9yIjpmYWxzZSwiaWF0IjoxNzE1MDYxOTQzLCJleHAiOjE3MTUxMTU5NDN9.pjoyh26762pn1R5Wi0Lgv0BrqwdNg-1fi4ft-tsyXZ0
###

GET http://95.130.227.160:3300/api/admin/
