POST http://95.130.227.160:3300/api/admin
Content-Type: application/json

{
    "name": "Sardor",
    "password": "uzb3",
    "confirm_password": "uzb3",
    "phone": "+0000"

}
###

POST http://95.130.227.160:3300/api/admin/login
Content-Type: application/json

{
    "phone": "+0000",
    "password": "uzb3"

}
###

POST http://localhost:3300/api/admin/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaXNfYWN0aXZlIjp0cnVlLCJpc19jcmVhdG9yIjpmYWxzZSwiaWF0IjoxNzE1MDY0NTk2LCJleHAiOjE3MTUxMTg1OTZ9.YNtdQcnu4h1ronDhwYJwDJ-1Su5WCyAammFj1a3FqT8
###

GET http://localhost:3300/api/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaXNfYWN0aXZlIjp0cnVlLCJpc19jcmVhdG9yIjpmYWxzZSwiaWF0IjoxNzE1MDY1MDUzLCJleHAiOjE3MTUxMTkwNTN9.Gry6n5135qSJfVAqxzd9EYS7mgE_gO5SzDRaMl3KPq4