POST http://95.130.227.160:3300/api/distributors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaXNfYWN0aXZlIjp0cnVlLCJpc19jcmVhdG9yIjpmYWxzZSwiaWF0IjoxNzE1MDY0MTUxLCJleHAiOjE3MTUxMTgxNTF9.6t1m8zXm-Dcn3LLbS7SHjD9hIIiN-5pjXiFSOauOYPo

{
    "company_name": "oqk",
    "email": "hello@gmail.com",
    "address": "Tashkent",
    "phone_number": "+88288",
    "working_years": 3,
    "license_image":"ika.img",
    "license_number": "998955551000"
}
###

GET http://95.130.227.160:3300/api/distributors/
###

PATCH http://localhost:3000/api/distributors/2
Content-Type: application/json

{
    "company_name": "Activist1",
    "email": "activist@gmail.com",
    "address": "Tashkent",
    "phone_number": "+998955551000",
    "working_years": 2
}
###

DELETE http://localhost:3000/api/distributors/2





