POST http://localhost:3000/api/ehson-type
Content-Type: application/json

{
    "name": "Yetimlar uchun",
    "description": "yigilgan pul yo'l qurilishi yoki uy uchun sarflanadi"
}
###

GET http://localhost:3000/api/ehson-type/
###

PATCH http://localhost:3000/api/ehson-type/1
Content-Type: application/json

{
    "name": "Ta'lim uchun1",
    "description": "eskirib qolgan maktabga remont uchun va oquv qurollari uchun mablag' kerak "
}
###

DELETE http://localhost:3000/api/ehson-type/2





