POST http://localhost:3000/api/replenish-wallet/4/add
Content-Type: application/json

{
    "replenish_amount": 501
}


###



POST http://localhost:3000/api/replenish-wallet/check-code
Content-Type: application/json

{
    "code": "860532"
}

