POST http://95.130.227.160:3300/api/social-distributor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaXNfYWN0aXZlIjp0cnVlLCJpc19jcmVhdG9yIjpmYWxzZSwiaWF0IjoxNzE1MDY1NjQxLCJleHAiOjE3MTUxMTk2NDF9.5XZpewRcrRaK2p3bfJ4OLaSzYG5eiUhKQzWJXp-3ZR0


{
    "social_id": 1,
    "distributor_id":1,
    "link": "instagram.com/realmuhammadjon"
}
###

GET http://95.130.227.160:3300/api/social-distributor/
###

PATCH http://localhost:3000/api/social-distributor/1
Content-Type: application/json

{
    "name": "instagram1",
    "logo": "instagram.png"
}
###

DELETE http://localhost:3000/api/social-distributor/1





