POST http://95.130.227.160:3300/api/social
Content-Type: application/json

{
    "name": "telegram",
    "logo": "telegram.png"
}
###

GET http://95.130.227.160:3300/api/social/
###

PATCH http://localhost:3000/api/social/1
Content-Type: application/json

{
    "name": "instagram1",
    "logo": "instagram.png"
}
###

DELETE http://localhost:3000/api/social/1





