POST http://localhost:3000/api/successfully-completed
Content-Type: application/json

{
  "date_event": "2024-05-05",
  "amount_spent": "25000000",
  "ehson": 1,
  "distributor": 1
}
###

GET http://localhost:3000/api/successfully-completed/
###

PATCH http://localhost:3000/api/successfully-completed/1
Content-Type: application/json

{
    "date_event": "2024-05-05",
    "amount_spent": "25000000",
    "ehson_id": 1,
    "distributor_id": 2
}
###

DELETE http://localhost:3000/api/successfully-completed/2





