POST http://localhost:3000/api/transaction-history
Content-Type: application/json

{
    "wallet_id": 3,
    "amount": "98000000",
    "type": "income",
    "date": "2017-02-03"
}
###

GET http://localhost:3000/api/transaction-history/
###

PATCH http://localhost:3000/api/transaction-history/1
Content-Type: application/json

{
    "wallet_id": 1,
    "amount": "98000001",
    "type": "out",
    "date": "2019-02-10"
}
###

DELETE http://localhost:3000/api/transaction-history/1





