POST http://localhost:3000/api/user-cards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaXNfYWN0aXZlIjp0cnVlLCJpYXQiOjE3MTUwMzM2MDMsImV4cCI6MTcxNTA4NzYwM30.ZZURoolplULD6RhgoGmT2tCvJDzQ1lc0qKNtPBQkjsY

{
    "card_number": "000000000002",
    "expire_date": "2026-02-03",
    "balance": 1000000,
    "is_main": true
}
###

GET http://localhost:3000/api/user-cards/
###

PATCH http://localhost:3000/api/user-cards/1
Content-Type: application/json

{
    "card_number": "98601020036542",
    "expire_date": "2026-02-03",
    "balance":"123456",
    "is_main": true
}
###

DELETE http://localhost:3000/api/user-cards/2





